// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xjczurecwdpfithurlsq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhqY3p1cmVjd2RwZml0aHVybHNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5ODU4NDAsImV4cCI6MjA3MDU2MTg0MH0.IH-Iu4h5alohfLsAJXG2TSw7frdOlCUOY7cYWcX8W8I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});